### ISSUE TITLE
Build hangs in CI env at `Upload Debug Symbols to Sentry`

### ISSUE THREAD

**Issue by softatac** [getsentry/sentry-react-native#1281]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [ ]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 0.0.0

**`react-native` version:** 0.63.4

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

---
**I have following issue:**

In CI environment (Github actions), using **fastlane** the build process gets stuck at the step `Upload Debug Symbols to Sentry`.
- Deployment is done via fastlane, e.g. `fastlane ios beta`
- On local machine it works fine
- With previous version of '@sentry/react-native' (v2.0.0) it worked perfectly, after upgrade to (v2.1.0) the problem appeared

**Steps to reproduce:**
- In a CI environemt, `fastlane ios beta`

**Actual result:**
Build stops at `Upload Debug Symbols to Sentry`, and enters timeout as the whole CI workflow is limited to 100 minutes

**Expected result:**

Upload debug symbols successfully.

---
github workflow
```yaml
beta-ios:
    name: iOS beta
    runs-on: macOS-latest
    timeout-minutes: 100
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '15.x'
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      # CACHE
      - name: Cache node_modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      - name: Cache cocoa pods
        uses: actions/cache@v1
        with:
          path: Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-
      - name: Cache ruby gems
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      # PREPARE
      - name: Dependencies install
        run: cd ios && bundle install
      - name: YARN install
        run: yarn
      - name: Cocoapods install
        run: cd ios && pod install
      - name: Git credentials for match
        uses: fusion-engineering/setup-git-credentials@v2
        with:
          credentials: ${{secrets.GIT_CREDENTIALS}}
      # BUILD & PUBLISH
      - name: Versioning, for fastlane
        run: |
          export BUILD_NUMBER=${{ github.run_id }}
          export VERSION_NUMBER=$(git describe --abbrev=0 --tags | sed 's/[a-zA-Z-]//g')
          export CHANGELOG_MESSAGE="$(<CHANGELOG_recent.md)"
          echo "::set-env name=BUILD_NUMBER::$BUILD_NUMBER"
          echo "::set-env name=VERSION_NUMBER::$VERSION_NUMBER"
          echo "::set-env name=CHANGELOG_MESSAGE::$CHANGELOG_MESSAGE"
          echo Build, number $BUILD_NUMBER, ver $VERSION_NUMBER \\n$CHANGELOG_MESSAGE
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      - name: Fastlane - build & publish BETA
        run: bundle exec fastlane ios beta
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
```

Fastlane Fastfile
```
ios_app_id          = CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier)
android_app_id      = CredentialsManager::AppfileConfig.try_fetch_value(:package_name)
slack_url           = 'XXX'
ENV['SLACK_URL'] = slack_url

build_number = ENV['BUILD_NUMBER']
version_number = ENV['VERSION_NUMBER']
changelog_message = ENV['CHANGELOG_MESSAGE']
force_ci = ENV['IS_CI']

default_platform(:ios)


# iOS #######################################
platform :ios do
  desc 'Sign for appstore'
  lane :certificatesSetup do
    if force_ci
      setup_ci(force: true)
      create_keychain(
        name: 'CI',
        password: 'XXX',
        default_keychain: true,
        unlock: true,
        timeout: 3600,
        add_to_search_list: true
      )
      match(
        type: 'appstore',
        keychain_name: 'CI',
        keychain_password: 'XXX'
      )
    else
      match(type: 'appstore')
    end
  end

  desc 'Build iOS app'
  private_lane :build do
    # versioning
    if build_number
      increment_build_number(build_number: build_number, xcodeproj: 'ios/StudentMobile.xcodeproj')
    end
    if version_number
      increment_version_number(version_number: version_number, xcodeproj: 'ios/StudentMobile.xcodeproj')
    end
    build_app(workspace: 'ios/StudentMobile.xcworkspace', scheme: 'StudentMobile')
  end



  desc 'Prepare metadata for AppStore'
  lane :prepareMetadata do
    if changelog_message 
      set_changelog(changelog: changelog_message, version: version_number)
    end
  end

  desc 'Build beta iOS app, to Test Flight'
  lane :beta do
    certificatesSetup
    build
    prepareMetadata
    upload_to_testflight(skip_submission: true)
    post_deploy(title: 'iOS Beta, pls test me')
  end

  desc 'Build & release iOS, to App Store'
  lane :release do
    certificatesSetup
    build
    prepareMetadata
    upload_to_app_store(
      skip_screenshots: true,
      skip_metadata: true,
      submit_for_review: true,
      automatic_release: true,
      submission_information: {
        export_compliance_platform: 'ios',
        export_compliance_app_type: 'ios',
        export_compliance_compliance_required: true,
        export_compliance_uses_encryption: true,
        export_compliance_contains_third_party_cryptography: true,
        export_compliance_available_on_french_store: false,
        add_id_info_serves_ads: true,
        add_id_info_uses_idfa: true,
        add_id_info_limits_tracking: true,
        # content_rights_contains_third_party_content: true,
        # content_rights_has_rights: true,
      }
    )
    post_deploy(title: 'iOS release/stable')
  end

  desc 'Post release notes to slack'
  lane :post_deploy do |options|
    title = options[:title]
    slack(
      message: "New iOS app successfully submitted for: " + title,
      default_payloads: [:git_branch, :last_git_commit_message],
      success: true,
      attachment_properties: {
        fields: [
          { title: "Version", value: version_number },
          { title: "Build number", value: build_number },
          { title: "Changelog", value: changelog_message },
        ]
      }
    )
  end
end
```
