### ISSUE TITLE
iOS build failing on Github actions with "An organization slug is required"

### ISSUE THREAD

**Issue by ShivamJoker** [getsentry/sentry-react-native#1899]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io) 

Which SDK and version?

macOS 11
Xcode 13
@sentry/react-native": "^3.1.1",
react-native": "0.66.1",

### Steps to Reproduce

1. Clone the repo or create your own basic setup - [repo](https://github.com/ShivamJoker/SQL-Play/tree/14-feat/e2e-testing)
2. Create a Github workflow - [mine](https://github.com/ShivamJoker/SQL-Play/blob/14-feat/e2e-testing/.github/workflows/e2e_ios.yml#L18)
3. If the workflow runs I get an error of build failing 

The build command is 
```sh
xcodebuild -workspace ios/Sql_Playground.xcworkspace -scheme SQL_PlayGround -configuration Release -sdk iphonesimulator -derivedDataPath ios/build
```

### Output
```sh
/bin/sh -c /Users/runner/work/SQL-Play/SQL-Play/ios/build/Build/Intermediates.noindex/SQL_PlayGround.build/Release-iphonesimulator/SQL_PlayGround.build/Script-00DD1BFF1BD5951E006B06BC.sh
 error: An organization slug is required (provide with --org)

Add --log-level=[info|debug] or export SENTRY_LOG_LEVEL=[info|debug] to see more output.
Please attach the full debug log to all bug reports.
```

### Expected Result
It should build the app as it is doing locally 

### Actual Result
The build keeps failing here is the [full log file](https://pipelines.actions.githubusercontent.com/hSKaCPwBLLX7MCIdyHugg8z3S1kXLnXLqAh8zedJXAK8edwsor/_apis/pipelines/1/runs/16/signedlogcontent/2?urlExpires=2021-11-17T08%3A40%3A03.8108816Z&urlSigningMethod=HMACV1&urlSignature=a0g%2Bts%2FjmMgUFghV1O0dzmlftMXcf7jQWkaOPKgX%2Fes%3D)
<img width="966" alt="image" src="https://user-images.githubusercontent.com/23727670/142167093-c325042f-859a-4173-bff0-e2f24b393121.png">

**Comment by marandaneto** [comment]
@ShivamJoker have you run the `@sentry/wizard`?

https://docs.sentry.io/platforms/react-native/#linking
looks like you are missing this steps since your repo https://github.com/ShivamJoker/SQL-Play/tree/14-feat/e2e-testing does not have the sentry.properties files

**Comment by ShivamJoker** [comment]
@marandaneto thats what I am doing the workflow reading the secret and creating `sentry.properties` in root and ios directory.

```yaml
        run: |
          echo $APP_ENV > '.env'
          echo $SENTRY_PROPERTIES > 'ios/sentry.properties'
          echo $SENTRY_PROPERTIES > 'sentry.properties'
          wc ios/sentry.properties 
```

To verify this i even added a word count

<img width="500" alt="image" src="https://user-images.githubusercontent.com/23727670/142170048-49abe83b-6cf6-4fb2-870e-aa911391e7ca.png">

I have used sentry-wizard to set this locally

**Comment by marandaneto** [comment]
something is fishy since it runs locally with the same setup, it's an issue with your CI or the way you set up the env. var.
our sample runs on CI just fine https://github.com/getsentry/sentry-react-native/blob/master/sample/ios/sentry.properties
the difference is that we export via env. var. only the token https://github.com/getsentry/sentry-react-native/blob/master/.github/workflows/e2e.yml#L8-L9

just to be clear, `SENTRY_PROPERTIES` should have the path of the file in the disk, and not the content of the file `sentry.properties` -> https://docs.sentry.io/product/cli/configuration/#properties-files

**Comment by ShivamJoker** [comment]
Alright I changed the env variable so that it doesn't conflict with `SENTRY_PROPERTIES` but still got the same error after it ran for 30 minutes 😢 

```yml
     - name: Setup secret files    
        env: 
          APP_ENV: ${{ secrets.APP_ENV }}
          SENTRY_CONFIG: ${{ secrets.SENTRY_PROPERTIES }}
        run: |
          echo $APP_ENV > '.env'
          echo $SENTRY_CONFIG > 'ios/sentry.properties'
          echo $SENTRY_CONFIG > 'android/sentry.properties'

```

Now I am trying with the token only, will update soon

**Comment by ShivamJoker** [comment]
@marandaneto I tried like how you guys have done but it didn't take the auth token :/

```
error: API request failed
 caused by: sentry reported an error: Authentication credentials were not provided. (http status: 401)
```

I did same like this
```yml
    steps:
      - uses: actions/checkout@v1

      - name: Setup secret files    
        env: 
          APP_ENV: ${{ secrets.APP_ENV }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        run: |
          echo $APP_ENV > '.env'

```
