### ISSUE TITLE
Add lint for java, objective-c, cocoa pods code

### ISSUE THREAD

**Issue by krystofwoldrich** [getsentry/sentry-react-native#2534]
### Description

Similar to kotlin lint in Dart.

https://github.com/getsentry/sentry-dart/blob/fe217baa64bf65dac702f8ef5acd8a267f02b46c/.github/workflows/flutter.yml#L191-L204

```yml
  pod-lint:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ./flutter
    steps:
      - uses: actions/checkout@v3
      # https://github.com/CocoaPods/CocoaPods/issues/5275#issuecomment-315461879
      - run: pod lib lint ios/sentry_flutter.podspec --configuration=Debug --skip-import-validation --allow-warnings

  swift-lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./flutter
    steps:
      - uses: actions/checkout@v3
      - uses: norio-nomura/action-swiftlint@9f4dcd7fd46b4e75d7935cf2f4df406d5cae3684 # pin@3.2.1

  ktlint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./flutter
    steps:
      - uses: actions/checkout@v3

      - name: ktlint
        uses: ScaCap/action-ktlint@f22fa77f33cbfaf0a1a332aae1f176c8712c8a3c # pin@1.4
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          android: true
```
