### ISSUE TITLE
Xcode build failing:  'RNSentrySpec.h' file not found

### ISSUE THREAD

**Issue by jforaker** [getsentry/sentry-react-native#2911]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [x ]  iOS
- [ ]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 5.1.1
**`react-native` version:** 0.69.8

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

```
cat Podfile.lock | grep Sentry

  - RNSentry (5.1.1):
    - Sentry/HybridSDK (= 8.3.0)
  - Sentry/HybridSDK (8.3.0):
    - SentryPrivate (= 8.3.0)
  - SentryPrivate (8.3.0)
  - "RNSentry (from `../node_modules/@sentry/react-native`)"
    - Sentry
    - SentryPrivate
  RNSentry:
  RNSentry: d4f5c1e27b9f00b21af8602883f88838452b8a59
  Sentry: 757565eb01e2a6ef6b26e897e4e47e8213e12f06
  SentryPrivate: 668d6ce46835769b32e61dc8b5c78ef0b6cdcef8
```

Hello folks. Has anyone ever experienced 'RNSentrySpec.h' file not found build error in XCode? I'm currently doing a project update to the new arch. Heres my installation steps:

```
yarn upgrade @sentry/react-native@5.1.1 --exact
npx @sentry/wizard@2 -i reactNative -p ios android
RCT_NEW_ARCH_ENABLED=1 pod install
```
After pod install Xcode build fails with that error. Any help is appreciated as this is the only build error holding us back at the moment (also paying customer on .io :D ) . I've followed the troubleshooting guides, read a million issues, been stuck for a day and half on this. 

```
'RNSentrySpec.h' file not found
```

![image](https://user-images.githubusercontent.com/2042031/226733001-b887b1fd-a13e-4b71-a294-6af27c49f70c.png)
