### ISSUE TITLE
How to upload SourceMaps for react-native-windows

### ISSUE THREAD

**Issue by creambyemute** [getsentry/sentry-react-native#3029]
**OS:**
- [x]  Windows
- [ ]  MacOS
- [ ]  Linux

**Platform:**
- [ ]  iOS
- [ ]  Android
- [x] Windows

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 4.15.0

**`react-native` version:** 0.65.3

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

---
**I have following issue:**

I am trying to upload the sourcemap for react-native-windows manually via sentry-cli in our azure pipeline (because it's not supported by default within the build-process).

I have added a bash step to our azure pipeline on windows

```
  - task: Bash@3
    displayName: "Upload SourceMaps to Sentry for Prod"
    condition: eq(variables.appenv, 'prod')
    inputs:
      targetType: 'inline'
      script: 'export SENTRY_PROPERTIES=$(Build.SourcesDirectory)\windows\sentry.properties && set -e &&  ./node_modules/@sentry/cli/bin/sentry-cli releases files inspection-windows@$(AppVersion).$(AppVersionCode) upload-sourcemaps --dist $(AppVersion).$(AppVersionCode) $(Build.SourcesDirectory)\windows\inspection\Bundle\index.windows.bundle $(Build.SourcesDirectory)\windows\Release\inspection\sourcemaps\react\index.windows.bundle.map'
```

**Steps to reproduce:**
- Init a project
- Add react-native-windows
- Add sentry
- Setup an azure pipeline
- Add task to upload sourcemap

**Actual result:**

Even though I'm exporting the SENTRY_PROPERTIES it's reporting an error on the Upload SourceMaps Task 
`error: An organization slug is required (provide with --org)`

**Expected result:**

Upload SourceMaps to sentry for react-native-windows.

Is there a way to provide sentry-cli with the sentry.properties file directly?

**Comment by creambyemute** [comment]
I got the sentry.properties working with 

```

  - task: PowerShell@2
    displayName: "Set Sentry Properties"
    inputs:
      targetType: 'inline'
      script: |
        # Write your PowerShell commands here.
      
        Write-Host "##vso[task.setvariable variable=SENTRY_PROPERTIES;]./windows/sentry.properties"
```

It's starting the upload but uploads no artifacts. I'll update and close the issue once I have this resolved as well.
