### ISSUE TITLE
Source code not found with successful CI jobs

### ISSUE THREAD

**Issue by chuenlum** [getsentry/sentry-react-native#732]
OS:
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

_Platform:_
- [x]  iOS
- [ ]  Android

SDK:
- [x]  `@sentry/react-native`
- [ ]  `react-native-sentry`

`react-native` version: 0.61.5

Init Code:

```
Sentry.init({
  debug: __DEV__,
  environment: Config.ENVIRONMENT,
  dsn: Config.DSN,
});
Sentry.setRelease(packageJSON.version);
Sentry.setDist(DeviceInfo.getBuildNumber());
```

---
I have following issue:

I'm setting up Sentry before any actual deployment, as part of a setup process for a project. Hence all of the below are done on a MacBook using simulator, terminal, VS Code editor, and Gitlab CI jobs.

I've set up Gitlab CI that runs jobs to bundle and create source maps, sentry releases, and send the artifacts to sentry.io. In sentry.io web UI, I see artifacts are uploaded with the specified distribution number.

<img width="1378" alt="release-artifacts" src="https://user-images.githubusercontent.com/12426535/71609088-bb0b0c00-2bc0-11ea-8ad1-2bc15179ccb1.png">

Issues also appear the All Issues tab as well. 

<img width="1372" alt="issues-associated" src="https://user-images.githubusercontent.com/12426535/71609091-c4947400-2bc0-11ea-81df-4f2bc08981dc.png">

For those issues that are associated, the `release` and `dist` matches up.

<img width="856" alt="issue-details" src="https://user-images.githubusercontent.com/12426535/71609096-c9f1be80-2bc0-11ea-831c-5ebaa815d7d6.png">

However, I get errors saying source code was not found:

<img width="942" alt="source-code-not-found" src="https://user-images.githubusercontent.com/12426535/71609135-07564c00-2bc1-11ea-9eec-e151e1f90398.png">

And the error trace doesn't show the paths to the files

<img width="922" alt="trace" src="https://user-images.githubusercontent.com/12426535/71609140-0ae9d300-2bc1-11ea-8991-24dc645d74fc.png">

CI jobs below:

```yaml
bundle:
  stage: bundle
  before_script:
    - yarn
  artifacts:
    paths:
      - build/ios/
    expire_in: 1 week
  script:
    - mkdir -p ./build/ios
    - ./node_modules/.bin/react-native bundle --platform ios --entry-file ./index.js --bundle-output ./build/ios/main.jsbundle --assets-dest ./build/ios/assets --sourcemap-output ./build/ios/main.jsbundle.map

sentry:
  stage: sentry
  image: getsentry/sentry-cli
  before_script: []
  dependencies:
    - bundle
  script:
    - echo "Create a new release using the package.json version number"
    - VERSION=$(cat package.json | grep version | head -1 | awk -F= "{ print $2 }" | sed -E 's/(version)|[:,\",]//g' | tr -d '[[:space:]]')
    - BUILD_NUMBER=$(cat ios/ProjectName/Info.plist | grep -A1 CFBundleVersion | grep string | sed 's/<[^>]*>//g')
    - export SENTRY_URL=$SENTRY_BASE_URL
    - export SENTRY_AUTH_TOKEN=$SENTRY_BASE_TOKEN
    - export SENTRY_ORG=$SENTRY_BASE_ORGANIZATION
    - export SENTRY_PROJECT=$SENTRY_BASE_PROJECT
    - sentry-cli releases new $VERSION
    - sentry-cli releases set-commits --auto $VERSION
    - sentry-cli releases files $VERSION upload-sourcemaps $CI_PROJECT_DIR/build/ios --ext jsbundle --ext map --validate --verbose --rewrite --strip-common-prefix --dist $BUILD_NUMBER --log-level debug
    - sentry-cli releases finalize $VERSION
    - echo "Finalized release"
```

And here's the prettified debug response body from the CI sentry job

```json
{
  "dateReleased": null,
  "commitCount": 1,
  "url": null,
  "data": {},
  "lastDeploy": null,
  "deployCount": 0,
  "dateCreated": "2019-12-31T02:50:58.639811Z",
  "lastEvent": "2019-12-31T02:50:58Z",
  "version": "0.0.1-sentry.3",
  "firstEvent": "2019-12-31T02:50:58Z",
  "lastCommit": {
    "repository": {
      "status": "active",
      "integrationId": "47417",
      "externalSlug": 15737469,
      "name": "<redacted>",
      "provider": {
        "id": "integrations:gitlab",
        "name": "Gitlab"
      },
      "url": "https://gitlab.com/projectname/mobile-app",
      "id": "51842",
      "dateCreated": "2019-12-28T08:51:40.993125Z"
    },
    "releases": [
      {
        "dateReleased": null,
        "url": null,
        "dateCreated": "2019-12-31T02:50:58.639811Z",
        "version": "0.0.1-sentry.3",
        "shortVersion": "0.0.1-sentry.3",
        "ref": null
      }
    ],
    "author": {
      "username": "<redacted>",
      "lastLogin": "2019-12-28T08:17:36.501593Z",
      "isSuperuser": false,
      "emails": [
        {
          "is_verified": false,
          "id": "623405",
          "email": "<redacted>"
        },
        {
          "is_verified": true,
          "id": "623401",
          "email": "<redacted>"
        }
      ],
      "isManaged": false,
      "lastActive": "2019-12-31T02:47:47.264878Z",
      "isStaff": false,
      "identities": [],
      "id": "573545",
      "isActive": true,
      "has2fa": false,
      "name": "ProjectName",
      "avatarUrl": "https://secure.gravatar.com/avatar/fcc94a18f4d0e47594ede091a01555e0?s=32&d=mm",
      "dateJoined": "2019-12-28T08:15:58.233245Z",
      "options": {
        "timezone": "Asia/Jakarta",
        "stacktraceOrder": -1,
        "language": "en",
        "clock24Hours": false
      },
      "flags": {
        "newsletter_consent_prompt": false
      },
      "avatar": {
        "avatarUuid": null,
        "avatarType": "letter_avatar"
      },
      "hasPasswordAuth": true,
      "email": "<redacted>"
    },
    "dateCreated": "2019-12-31T02:55:34Z",
    "message": "tweak: set dist number in Sentry event",
    "id": "4bebf77ac59e07669e41515ed3879ad4fdcb63ed"
  },
  "shortVersion": "0.0.1-sentry.3",
  "authors": [
    {
      "username": "<redacted>",
      "lastLogin": "2019-12-28T08:17:36.501593Z",
      "isSuperuser": false,
      "emails": [
        {
          "is_verified": false,
          "id": "623405",
          "email": "<redacted>"
        },
        {
          "is_verified": true,
          "id": "623401",
          "email": "<redacted>"
        }
      ],
      "isManaged": false,
      "lastActive": "2019-12-31T02:47:47.264878Z",
      "isStaff": false,
      "identities": [],
      "id": "573545",
      "isActive": true,
      "has2fa": false,
      "name": "ProjectName",
      "avatarUrl": "https://secure.gravatar.com/avatar/fcc94a18f4d0e47594ede091a01555e0?s=32&d=mm",
      "dateJoined": "2019-12-28T08:15:58.233245Z",
      "options": {
        "timezone": "Asia/Jakarta",
        "stacktraceOrder": -1,
        "language": "en",
        "clock24Hours": false
      },
      "flags": {
        "newsletter_consent_prompt": false
      },
      "avatar": {
        "avatarUuid": null,
        "avatarType": "letter_avatar"
      },
      "hasPasswordAuth": true,
      "email": "<redacted>"
    }
  ],
  "owner": null,
  "newGroups": 0,
  "ref": null,
  "projects": [
    {
      "slug": "projectname",
      "name": "projectname"
    }
  ]
}
```

**Steps to reproduce:**
- create react native project
- create CI using above jobs
- push, check that artifacts, version, distribution number match in sentry.io UI
- on local computer, launch the iOS simulator, throw an error (e.g. onPress button click)
- observe the resulting issue details in sentry.io

**Actual result:**
- Errors saying source code was not found
- Trace shows `app:///` instead of path to file

**Expected result:**
- No errors
- Trace showing path to source file and code snippet
