### ISSUE TITLE
Source code was not found

### ISSUE THREAD

**Issue by ygrishajev** [getsentry/sentry-react-native#845]
**OS**: Linux

**Platform:**
- iOS
- Android

**SDK**:
`@sentry/react-native`: ^1.3.0

**Are you using Expo?**: No

**Are you using sentry.io or on-premise?**: sentry.io (SaaS)

**Configuration**:
- app configuration
```javascript
import * as Sentry from '@sentry/react-native'
import codePush from 'react-native-code-push'
import { Platform } from 'react-native'

import env from '@peakers/react-native-env'

export const configure = userStore => {
  if (env.ENV === 'development') {
    return
  }

  const { CIRCLE_TAG } = env

  Sentry.init({
    dsn: '.....',
    environment: env.ENV
  })
  Sentry.setTags({
    tag: CIRCLE_TAG,
    commit: env.CIRCLE_SHA1
  })
  userStore.userValueChanges.subscribe(value => {
    if (value) {
      Sentry.setUser({
        id: String(value.id),
        email: value.email
      })
    }
  })

  codePush.getUpdateMetadata().then(update => {
    if (update) {
      Sentry.setRelease(`${env.APP_BUNDLE_ID}.${Platform.OS}:${CIRCLE_TAG}`)
    }
  })
}
```

- CI configuration iOS
```yaml
- run:
   name: CodePush
   command: |
         appcenter login --token $APPCENTER_API_TOKEN
         deployment="$([[ $CIRCLE_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+-cp$ ]] && echo Production || echo Staging)"
         appcenter codepush release-react -a $APPCENTER_APP_IOS -d $deployment --plist-file=$IOS_PLIST_PATH --output-dir ./ios/build
- run:
   name: Upload sourcemaps to Sentry
   command: |
         export SENTRY_PROPERTIES=./ios/sentry.properties
         node_modules/.bin/sentry-cli react-native appcenter $APPCENTER_APP_IOS ios ./ios/build/CodePush --release-name $APP_BUNDLE_ID.ios:$CIRCLE_TAG --log-level=TRACE
```

- CI configuration Android
```yaml
- run:
   name: CodePush
   command: |
      appcenter login --token $APPCENTER_API_TOKEN
      deployment="$([[ $CIRCLE_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+-cp$ ]] && echo Production || echo Staging)"
      appcenter codepush release-react -a $APPCENTER_APP_ANDROID -d $deployment --output-dir ./android/build
- run:
   name: Upload source maps to Sentry
   command: |
      export SENTRY_PROPERTIES=./android/sentry.properties
      node_modules/.bin/sentry-cli react-native appcenter $APPCENTER_APP_ANDROID android ./android/build/CodePush --release-name $APP_BUNDLE_ID.android:$CIRCLE_TAG --log-level=TRACE
```

---
**I have following issue**: source code is not being resolved for applications with code push applied.
Here are 2 *releases*:
[android](https://sentry.io/organizations/peakers/releases/ai.peakersinc.peakers.android%3Av0.3.18-cp/all-events/?environment=production)
[ios](https://sentry.io/organizations/peakers/releases/ai.peakersinc.peakers.ios%3Av0.3.18-cp/all-events/?environment=production)

On first start error fires with proper stack traces and once code push it does not resolve source maps. Artifacts are uploaded properly and are present in release artifacts in dashboard.
I've tried all the stuff from troubleshooting guide:
1) release is definitely configured as stated above and it is there in dashboard
2) sourceMappingURL is present and matches sourceMappingURL value
_IOS_:
  directive: `//# sourceMappingURL=main.jsbundle.map`
  bundle name: `~/main.jsbundle`
  source map name: `~/main.jsbundle.map`
_ANDROID_:
  directive: `//# sourceMappingURL=index.android.bundle.map`
  bundle name: `~/index.android.bundle`
  source map name: `~/index.android.bundle.map`
2) release is definitely configured as stated above and it is there in dashboard
3) in JSON stack trace frames are: `abs_path: "app:///main.jsbundle"`
4) artifacts are uploaded before errors occur (tested with a bunch of errors)
5) sourcemaps are verified to be working locally
6) sourcemaps are much less than 40MB
7) no compression
8) my head aches for quite long because of this issue so I've tried a lot of other stuff described in this repo's issues.

**Steps to reproduce:**
- Configure application as stated above
- Deploy
- codepush
- upload source maps as stated above
- catch exception in app

**Actual result:**
- Error is displayed in sentry dashboard with minified unusable stack trace

**Expected result:**
- Error is displayed in sentry dashboard with verbose stack trace
